### ISSUE TITLE
NameError: name 'fastText' is not defined.

### ISSUE THREAD

**Issue by nnakamura3** [toshohirasawa/nmtpytorch-emb-pred#3]
HI, when i try to run the example/nmt.conf, I got the following error.
I checked the corresponding code, but I couldn't find a way to solve it.
If you have any idea, please give me a hand.

```
Traceback (most recent call last):
  File "bin/nmtpy", line 181, in <module>
    loop = MainLoop(model, opts.train, dev_mgr)
  File "/disk/n.nakamura/mmt-emb-pred/nmtpytorch/mainloop.py", line 61, in __init__
    self.model.reset_parameters()
  File "/disk/n.nakamura/mmt-emb-pred/nmtpytorch/models/pw/nmt.py", line 152, in reset_parameters
    self.enc.emb.weight = load_param_from_fasttext(self.trg_vocab, args)
  File "/disk/n.nakamura/mmt-emb-pred/nmtpytorch/utils/embedding.py", line 95, in load_param_from_fasttext
    normalize=True, center_type=center_type, sub_pca=sub_pca, pca_size=n_pca).cuda()
  File "/disk/n.nakamura/mmt-emb-pred/nmtpytorch/utils/embedding.py", line 30, in load_fasttext
    model = fastText.load_model(bin_fname)
NameError: name 'fastText' is not defined
```

**Comment by nnakamura3** [comment]
I solved this problem by converting "fastText" in mmt-emb-pred/nmtpytorch/utils/embedding.py into "fasttext"
